---
version: "3"

# silent: true

includes:
  c: https://raw.githubusercontent.com/standardloop/taskfiles/refs/heads/main/c.yml # can pin in future
  # c: ../taskfiles/c.yml

vars:
  SOURCE_FILES:
    - json.c
    - lexer.c
    - parser.c
  TEST_EXECUTABLE_NAME: test
  TEST_SOURCE_FILES:
    - json.test.c
    - lexer.test.c
    - parser.test.c
  DYLIB_NAME: libstandardloop-json.dylib
  DYLIB_HEADER: json.h
  DYN_LIBS_USED: "-lstandardloop-util -lstandardloop-collections"

tasks:
  default:
    cmds:
      - task: test:build

  # GH_RELEASE_VERSION is set by CI
  release:
    deps:
      - dependencies
    cmds:
      - task: c:release

  dependencies:
    cmds:
      - task: c:dependencies:util
      - task: c:dependencies:collections

  test:
    deps:
      - test:run

  sanitize:
    deps:
      - test:run-sanitize

  test:build-sanitize:
    deps:
      - dependencies
      - c:dependencies:testing
    cmds:
      - task: c:test:build-sanitize

  test:run-sanitize:
    deps:
      - test:build-sanitize
    cmds:
      - ./{{.TEST_EXECUTABLE_NAME}}-sanitize

  test:build:
    deps:
      - dependencies
      - c:dependencies:testing
    cmds:
      - task: c:test:build

  test:run:
    deps:
      - test:build
    cmds:
      - ./{{.TEST_EXECUTABLE_NAME}}

  clean:
    deps:
      - c:test:clean

  fmt:
    deps:
      - c:fmt

  docs:
    silent: true
    cmds:
      - task: c:docs

  test:leaks:
    aliases:
      - leaks
    desc: "Run macOS leaks on the test program."
    deps:
      - test:build
    cmds:
      - cp /usr/local/lib/standardloop/libstandardloop-util.dylib ./
      - cp /usr/local/lib/standardloop/libstandardloop-collections.dylib ./
      - leaks --atExit -- ./{{.TEST_EXECUTABLE_NAME}}
      - rm libstandardloop-util.dylib
      - rm libstandardloop-collections.dylib
