---
version: "3"

# silent: true

includes:
  c: https://raw.githubusercontent.com/standardloop/taskfiles/refs/heads/main/c.yml # can pin in future
  # c: ../taskfiles/c.yml

vars:
  SOURCE_FILES:
    - json.c
    - lexer.c
    - parser.c
    - hashmap.c
    - dynamicarray.c
  TEST_EXECUTABLE_NAME: test
  TEST_SOURCE_FILES:
    - json.test.c
    - lexer.test.c
    - parser.test.c
  DYLIB_NAME: libstandardloop-json.dylib
  DYLIB_HEADER: json.h
  DYN_LIBS_USED: "-lstandardloop-util -lstandardloop-collections"

tasks:
  default:
    cmds:
      - task: test:build

  # GH_RELEASE_VERSION is set by CI
  release:
    deps:
      - dependencies
    cmds:
      - task: c:release

  dependencies:
    cmds:
      - task: c:dependencies:util
      - task: c:dependencies:collections

  test:
    deps:
      - test:run

  test:build-sanitize:
    deps:
      - dependencies
    cmds:
      - task: c:test:build-sanitize
  test:build:
    deps:
      - dependencies
    cmds:
      - task: c:test:build

  test:run:
    deps:
      - test:build
    cmds:
      - ./{{.TEST_EXECUTABLE_NAME}}

  clean:
    deps:
      - c:test:clean

  fmt:
    deps:
      - c:fmt

  docs:
    deps:
      - c:docs:moxygen
